# Generated by Django 2.0.6 on 2018-06-10 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_borrower_grouptouser_transaction_usertransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(default='', max_length=300)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Expense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='app.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
        ),
        migrations.RenameField(
            model_name='grouptouser',
            old_name='users',
            new_name='user',
        ),
    ]
