# Generated by Django 2.0.6 on 2018-06-10 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180610_0712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='app.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='app.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='user',
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
